version: "3.9"

networks:
  wp-net:

services:
  db:
    image: mariadb:10.4
    volumes:
      - ./build/docker/db:/var/lib/mysql
    networks:
      - wp-net
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass

  wp-app:
    depends_on:
      - db
    image: wordpress:php8.1-apache
    volumes:
      - ./build/docker/wp:/var/www/html
      - ./packages:/var/www/html/wp-content/themes
    ports:
      - "8088:80"
    networks:
      - wp-net
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpress

